version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    environment:
      - SERVER_ENV=beta
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - postgres

  postgres:
    image: kartoza/postgis:11.0-2.5
    restart: always
    env_file:
      - .env.example
    ports:
      - 15436:5432
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/

  nginx:
    restart: always
    build: docker/nginx/
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8123:80
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis/data:/data
    # command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

  celery:
    restart: always
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: celery -A config worker -l info

  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: celery -A config beat -l info -S django

volumes:
  static_volume:
  media_volume:
